MOBILES_BUTTON_1 = 'css=#litp18890259'
MOBILES_BUTTON_2 = 'xpath=//span[contains(text(), "Mobilní")]'
IPHONE_13_BLACK = 'css=#img6731111'
ADD_TO_CART = 'css=a[data-detail-wear="New"]'
CART_ICON = 'css=a[data-testid="headerBasketIcon"]'
PRODUCT_IN_CART = 'css=a.mainItem'
PRODUCT_SUBTRACT = 'css=div.countMinus'
CONFIRM_REMOVE = 'css=span[class*="green"][role="button"]'
HOMEPAGE_LOGO = 'css=a[data-testid="headerLogo"]'
